### ISSUE TITLE
Pyspark write to kafka topic with confluent schema throws Not a Union

### ISSUE THREAD

**Issue by sivasai-quartic** [AbsaOSS/ABRiS#125]
I have a dataframe with key,value as columns. I wanted to write to kafka with confluent_avro serialization. 
here is the snippet of code.
```
def convert_df_to_avro(self, spark_context, data_frame, schema_registry_url, topic):
        jvm_gateway = spark_context._gateway.jvm
        abris_avro  = jvm_gateway.za.co.absa.abris.avro
        naming_strategy = getattr(getattr(abris_avro.read.confluent.SchemaManager, "SchemaStorageNamingStrategies$"), "MODULE$").TOPIC_NAME()
        schema_registry_config_dict = {"schema.registry.url": schema_registry_url,
                                       "schema.registry.topic": topic,
                                       "value.schema.id": "latest",
                                       "value.schema.naming.strategy": naming_strategy}

        conf_map = getattr(getattr(jvm_gateway.scala.collection.immutable.Map, "EmptyMap$"), "MODULE$")
        for k, v in schema_registry_config_dict.items():
            conf_map = getattr(conf_map, "$plus")(jvm_gateway.scala.Tuple2(k, v))

        serialized_df = data_frame.select(Column(abris_avro.functions.to_confluent_avro(data_frame._jdf.col("value"), conf_map))
                                            .alias("value"))

        return serialized_df
```

```
Caused by: org.apache.avro.AvroRuntimeException: Not a union: {schema from confluent}
	at org.apache.avro.Schema.getTypes(Schema.java:299)
	at org.apache.spark.sql.avro.AvroSerializer.org$apache$spark$sql$avro$AvroSerializer$$resolveNullableType(AvroSerializer.scala:229)
	at org.apache.spark.sql.avro.AvroSerializer.<init>(AvroSerializer.scala:48)
	at za.co.absa.abris.avro.sql.CatalystDataToAvro.serializer$lzycompute(CatalystDataToAvro.scala:44)
	at za.co.absa.abris.avro.sql.CatalystDataToAvro.serializer(CatalystDataToAvro.scala:43)
	at za.co.absa.abris.avro.sql.CatalystDataToAvro.nullSafeEval(CatalystDataToAvro.scala:49)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.serializefromobject_doConsume_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:858)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:858)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
Does this function to_confluent_avro available in pyspark ? even in readme also mentioned as to read from kafka, what about the write ?
if available, can any one please provide example ?

**Comment by cerveada** [comment]
Hello,
yes it´s available. Which version of Abris and Spark are you using?

**Comment by sivasai-quartic** [comment]
I'm using 2.4.5 spark and abris 3.2.0

**Comment by sivasai-quartic** [comment]
Able to resolve by changing nullability of data frame column. changing to false is working

**Comment by sivasai-quartic** [comment]
@cerveada below is the error trace and the nullability of column is True. Able to resolve this by changing it to false. But any chances without changing this. Because I have to recreate the data frame by converting to rdd and applying the df schema. 

```
Caused by: org.apache.avro.AvroRuntimeException: Not a union: "string"
	at org.apache.avro.Schema.getTypes(Schema.java:299)
	at org.apache.spark.sql.avro.AvroSerializer.org$apache$spark$sql$avro$AvroSerializer$$resolveNullableType(AvroSerializer.scala:229)
	at org.apache.spark.sql.avro.AvroSerializer.<init>(AvroSerializer.scala:48)
	at za.co.absa.abris.avro.sql.CatalystDataToAvro.serializer$lzycompute(CatalystDataToAvro.scala:44)
	at za.co.absa.abris.avro.sql.CatalystDataToAvro.serializer(CatalystDataToAvro.scala:43)
	at za.co.absa.abris.avro.sql.CatalystDataToAvro.nullSafeEval(CatalystDataToAvro.scala:49)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:117)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:116)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1394)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:146)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:67)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:66)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Is it a bug or some thing else ?

**Comment by cerveada** [comment]
In Avro if you want some type to be nullable it has to be defined in a schema as a union. For example:
```
{ "name" : "foo", "type": ["string", "null"] }
```
If the type in the schema is just `string` it means this field is not nullable and that is the reason why you got this Exception.

**Comment by sivasai-quartic** [comment]
@cerveada yeah, I understood this part. but I don't want key and value should not be null and those fields are not null actually, I mean data is present. looks like because of the nullability of the column facing the issue. any fix for this?

**Comment by cerveada** [comment]
I think this is a correct behaviour. Data type of the data frame and schema is not compatible and therefore the error is thrown. If you say the column should not be null then it should be (nullable = false)

**Comment by brandon-stanley** [comment]
@sivasai-quartic How were you able to squash all your columns into a single column (i.e. the "value" column that Kafka expects) or did you not require this?

For additional context, I am trying to write records from a data frame (Example Schema: first_name, last_name, age), however, I need to _squash_ my records into a single column ("value") before serializing the data via the `to_confluent_avro` function. Is there a way to perform this operation in an efficient way?

**Comment by cerveada** [comment]
@brandon-stanley You can do it the same way as it's done in the documentation.
https://github.com/AbsaOSS/ABRiS/blob/master/documentation/confluent-avro-documentation.md#spark-to-avro

**Comment by doug-slalom** [comment]
@cerveada Would you be able to provide an example in PySpark for the spark-to-avro?

**Comment by Vincent-Zeng** [comment]
See https://issues.apache.org/jira/browse/SPARK-27838.

**Comment by cerveada** [comment]
@doug-slalom I am busy with other project right now, but I created ticket for it #128. 

It shouldn't be too hard to convert the Scala code to python if you check the py4j documentation: https://www.py4j.org/
Or maybe someone who did it already will share an example?

**Comment by cerveada** [comment]
@Vincent-Zeng Interesting, but it means it is Spark feature not really Abris one. If you use Spark 3.0.0 with Abris it should be fixed there. 

The newest version of Abris (3.2.1) should work with Spark 3.0.0

**Comment by Vincent-Zeng** [comment]
> @Vincent-Zeng Interesting, but it means it is Spark feature not really Abris one. If you use Spark 3.0.0 with Abris it should be fixed there.
> 
> The newest version of Abris (3.2.1) should work with Spark 3.0.0

Yeah. I build a package base on `spark 2.4.x`  with the `PR` code and it works.

**Comment by sivasai-quartic** [comment]
yeah @cerveada. It's working fine with spark 3 with nullable fields, but it's throwing Warning message. I'm using 3.2.0 abris with spark3.0. Just curious about how are this to_avro and from_avro working internally. Does it call schema registry API for every column serialization/deserialization in the data frame?

**Comment by cerveada** [comment]
Generally when you provide a schema coordinates each call of `to_avro` and `from_avro` should call schema registry just once.

Special case is when you are receiving confluent avro data. In this case the schema id is in the message so the schema must be downloaded after the message is received, that should happen once per each spark executor.

Older Abris versions were contacting schema registry more than necessary. So, use the newest version 2.3.+ if possible.

**Comment by cerveada** [comment]
I think we got off a topic a lot. So I will close this ticket and if you have additional questions please open new ticket for it.
