### ISSUE TITLE
Pyspark download confluent Schema registry and convert to sql struct throws TypeError

### ISSUE THREAD

**Issue by sivasai-quartic** [AbsaOSS/ABRiS#126]
Unable to use struct field in the python as it is a java object

```
def download_schema(self, spark_context, schema_registry_url, topic):

        jvm_gateway = spark_context._gateway.jvm
        abris_avro  = jvm_gateway.za.co.absa.abris.avro
        naming_strategy = getattr(getattr(abris_avro.read.confluent.SchemaManager, "SchemaStorageNamingStrategies$"), "MODULE$").TOPIC_NAME()
        schema_registry_config_dict = {"schema.registry.url": schema_registry_url,
                                       "schema.registry.topic": topic,
                                       "value.schema.id": "latest",
                                       "value.schema.naming.strategy": naming_strategy}
        conf_map = getattr(getattr(jvm_gateway.scala.collection.immutable.Map, "EmptyMap$"), "MODULE$")
        for k, v in schema_registry_config_dict.items():
            conf_map = getattr(conf_map, "$plus")(jvm_gateway.scala.Tuple2(k, v))
        schemaManager = abris_avro.read.confluent.SchemaManagerFactory.create(conf_map)
        schema = schemaManager.downloadSchema()
        sqlSchema = abris_avro.format.SparkAvroConversions.toSqlType(schema)
        return sqlSchema

schema = download_schema(**)
DF= spark.createDataFrame(rdd, schema)
```

```
TypeError: schema should be StructType or list or None, but got: StructType(StructField())at py4j.Protocol.getReturnValue(Protocol.java:473)
	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:108)
	at com.sun.proxy.$Proxy16.call(Unknown Source)
	at org.apache.spark.sql.execution.streaming.sources.PythonForeachBatchHelper$$anonfun$callForeachBatch$1.apply(ForeachBatchSink.scala:55)
	at org.apache.spark.sql.execution.streaming.sources.PythonForeachBatchHelper$$anonfun$callForeachBatch$1.apply(ForeachBatchSink.scala:55)
	at org.apache.spark.sql.execution.streaming.sources.ForeachBatchSink.addBatch(ForeachBatchSink.scala:35)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5$$anonfun$apply$17.apply(MicroBatchExecution.scala:537)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5.apply(MicroBatchExecution.scala:535)
	at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:534)
```

How to fetch the struct type from <class 'py4j.java_gateway.JavaObject'> to create a dataframe ?

using spark 2.4.5 and abris 3.2.0.

**Comment by cerveada** [comment]
You are not supposed to use `abris_avro.format.SparkAvroConversions.toSqlType` directly. It's an internal object of Abris. I mean you can do it if you want, but it's not supported Abris feature.

What do you want to achieve actually? Do you want to convert to Avro or from Avro or not at all?

**Comment by sivasai-quartic** [comment]
I have an RDD  and Wanted to create a data frame from Avro schema downloads from the schema registry in pyspark

**Comment by cerveada** [comment]
I see. It actually is in read.me. OK, my bad, but this part of read.me seems to be outdated.

Instead of 
```
abris_avro.format.SparkAvroConversions.toSqlType
```
try
```
SchemaConverters.toSqlType(avroSchema).dataType
```
(This is Scala thought, convert it to python) You can check `AvroDataToCatalyst` to see how it's used there.

**Comment by sivasai-quartic** [comment]
@cerveada Not sure how to convert it to python. I have tried like below. but it is throwing errror even though I passed spark-avro and spark-sql jars

```
sqlSchema = jvm_gateway.org.apache.spark.sql.avro.SchemaConverterstoSqlType(schema).dataType
TypeError: 'JavaPackage' object is not callable
```
can you please help me with that

**Comment by sivasai-quartic** [comment]
@cerveada  able to resolve 

```
sqlSchema = jvm_gateway.org.apache.spark.sql.avro.SchemaConverters.toSqlType(schema).dataType()
finalSchema = _parse_datatype_json_string(sqlSchema.json())
```

Thanks

closing this
