### ISSUE TITLE
ClassNotFoundException: org.apache.spark.sql.avro.SchemaConverters

### ISSUE THREAD

**Issue by ottensjors** [AbsaOSS/ABRiS#142]
Hi All,

currently working with following setup:

Spark 2.4.6 (with hadoop 3.1) 
scala 2.11
confluent schema-registry

used following cmd to start spark:

```
spark-shell --repositories https://packages.confluent.io/maven --packages org.apache.spark:spark-avro_2.11:2.4.6,org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.6,za.co.absa:abris_2.11:3.2.1
```
using avro-library v 1.8.2

import the following in spark-shell:

```
import org.apache.spark.sql.avro._
import org.apache.spark.sql.avro.schema
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._
import za.co.absa.abris.avro.functions.from_confluent_avro
import za.co.absa.abris.avro.read.confluent.SchemaManager
import za.co.absa.abris.avro.functions.to_confluent_avro
import org.apache.spark.sql.{DataFrame, Dataset, SparkSession}
```
set the following config:
```
val servers="kafka-server:9092"
val topic="dbserver1.public.product_product"

val commonRegistryConfig = Map(
  SchemaManager.PARAM_SCHEMA_REGISTRY_TOPIC -> "dbserver1.public.product_product",
  SchemaManager.PARAM_SCHEMA_REGISTRY_URL -> "http://kafkaschemaregistry-server:8081"
)

val keyRegistryConfig = commonRegistryConfig ++ Map(
  SchemaManager.PARAM_KEY_SCHEMA_NAMING_STRATEGY -> "topic.record.name",
  SchemaManager.PARAM_KEY_SCHEMA_ID -> "latest",
  SchemaManager.PARAM_KEY_SCHEMA_NAME_FOR_RECORD_STRATEGY -> "key"
)

val valueRegistryConfig = commonRegistryConfig ++ Map(
  SchemaManager.PARAM_VALUE_SCHEMA_NAMING_STRATEGY -> "topic.name",
  SchemaManager.PARAM_VALUE_SCHEMA_ID -> "latest"
)
```
i'm able to create a streaming dataframe:
```
val df=spark.readStream.format("kafka").option("kafka.bootstrap.servers", servers).option("subscribe", topic).option("startingOffsets", "earliest").load()    
```
however, when wanting to apply the schemas by following syntax:
```
val data = df.select(from_confluent_avro(col("value"), valueRegistryConfig))
```

i get following exception:

```
val data = df.select(from_confluent_avro(col("value"), valueRegistryConfig))
java.lang.NoClassDefFoundError: org/apache/spark/sql/avro/SchemaConverters$
  at za.co.absa.abris.avro.sql.AvroDataToCatalyst.dataType$lzycompute(AvroDataToCatalyst.scala:45)
  at za.co.absa.abris.avro.sql.AvroDataToCatalyst.dataType(AvroDataToCatalyst.scala:45)
  at org.apache.spark.sql.catalyst.expressions.Alias.toAttribute(namedExpressions.scala:176)
  at org.apache.spark.sql.catalyst.plans.logical.Project$$anonfun$output$1.apply(basicLogicalOperators.scala:52)
  at org.apache.spark.sql.catalyst.plans.logical.Project$$anonfun$output$1.apply(basicLogicalOperators.scala:52)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at org.apache.spark.sql.catalyst.plans.logical.Project.output(basicLogicalOperators.scala:52)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.schema$lzycompute(QueryPlan.scala:158)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.schema(QueryPlan.scala:158)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:79)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withPlan(Dataset.scala:3412)
  at org.apache.spark.sql.Dataset.select(Dataset.scala:1340)
  ... 49 elided
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.avro.SchemaConverters$
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 66 more
```

any ideas on how to fix this?

**Comment by ottensjors** [comment]
Hi Guys,

Got it working. had to use avro 1.9.2 over 1.8.2 library.

All good.

please consider this issue closed.

**Comment by cerveada** [comment]
Hi, 
hmm, this is strange. Do you know why you need 1.9.2?

Your setup looks ok. `SchemaConverters` is in `org.apache.spark:spark-avro_2.11` so it should be present on the classpath.
