### ISSUE TITLE
"Cannot evaluate expression: NamePlaceholder" when extracting Avro schema from multiple columns

### ISSUE THREAD

**Issue by felipemmelo** [AbsaOSS/ABRiS#170]
```scala
import org.apache.spark.sql.DataFrame
import org.scalatest.FunSuite
import za.co.absa.utils.spark.test.SparkSessionFixture
import org.apache.spark.sql.avro.SchemaConverters.toAvroType
import org.apache.spark.sql.functions.struct

case class TestData(name: String, id: Int)

class TestConversion extends FunSuite with SparkSessionFixture {

  test(testName = "whatever") {
    val data = getTestDataFrame()
    data.show()
    print(getSchema(data))
  }

  private def getTestDataFrame(): DataFrame = {
    val testData = Seq(
      TestData("a", 1),
      TestData("b", 2),
      TestData("c", 3)
    )

    spark.createDataFrame(testData)
  }

  private def getSchema(data: DataFrame) = {
    val columns = struct(data.columns.head, data.columns.tail: _*)
    val expression = columns.expr
    toAvroType(expression.dataType, expression.nullable)
  }
}
```

is throwing

```scala
Cannot evaluate expression: NamePlaceholder
java.lang.UnsupportedOperationException: Cannot evaluate expression: NamePlaceholder
	at org.apache.spark.sql.catalyst.expressions.Unevaluable$class.eval(Expression.scala:258)
	at org.apache.spark.sql.catalyst.expressions.NamePlaceholder$.eval(complexTypeCreator.scala:317)
	at org.apache.spark.sql.catalyst.expressions.CreateNamedStructLike$$anonfun$names$1.apply(complexTypeCreator.scala:363)
	at org.apache.spark.sql.catalyst.expressions.CreateNamedStructLike$$anonfun$names$1.apply(complexTypeCreator.scala:363)
	at scala.collection.immutable.List.map(List.scala:273)
	at org.apache.spark.sql.catalyst.expressions.CreateNamedStructLike$class.names(complexTypeCreator.scala:363)
	at org.apache.spark.sql.catalyst.expressions.CreateNamedStruct.names$lzycompute(complexTypeCreator.scala:425)
	at org.apache.spark.sql.catalyst.expressions.CreateNamedStruct.names(complexTypeCreator.scala:425)
	at org.apache.spark.sql.catalyst.expressions.CreateNamedStructLike$class.dataType(complexTypeCreator.scala:370)
	at org.apache.spark.sql.catalyst.expressions.CreateNamedStruct.dataType$lzycompute(complexTypeCreator.scala:425)
	at org.apache.spark.sql.catalyst.expressions.CreateNamedStruct.dataType(complexTypeCreator.scala:425)
	at org.apache.spark.sql.catalyst.expressions.CreateNamedStruct.dataType(complexTypeCreator.scala:425)
```

Probably because running 

```scala
val expression = columns.expr
```

is resulting in 

```scala
named_struct(NamePlaceHolder(), name, NamePlaceHolder(), id)
```

**Comment by cerveada** [comment]
Just a quick idea, could you try the following code?
```Scala
val data2 = data.select(struct(dataFrame.columns.head, dataFrame.columns.tail: _*) as 'value)
val schema = AvroSchemaUtils.toAvroSchema(data2, "value")
```

**Comment by felipemmelo** [comment]
That one worked. Thanks! Maybe that should be the only documented way? Looks more expressive, actually.

**Comment by kevinwallimann** [comment]
Had a similar issue. I had to replace
```
val allColumns = struct(dataFrame.columns.head, dataFrame.columns.tail: _*)
dataFrame.select(to_avro(allColumns, toAvroConfig) as 'value)
```
with

```
val allColumns = dataFrame.columns.map(c => dataFrame(c))
val allColumnsStruct = struct(allColumns: _*)
dataFrame.select(to_avro(allColumnsStruct, toAvroConfig) as 'value)
```

See https://github.com/AbsaOSS/hyperdrive/pull/175/files#diff-477504693d7083921936aaf7fc7d41023eb0719532ac0bc8df56cff5c1055aec

**Comment by cerveada** [comment]
I will reopen this, because we should deal with this somehow. At minimum update the docs.

**Comment by cerveada** [comment]
I was curious why some methods works and some not. Pay attention to type:
```Scala
val dfColumns: Array[String] = dataFrame.columns
val mapColumns: Array[Column] = dataFrame.columns.map(c => dataFrame(c)) // this works
```

- The first one just returns column names. That may be useful for select where you can select columns by name, but it's not possible to extract the type/schema of the column from that because it's just simple string.
- The second one returns actual column objects, that contain column type.

**Comment by kevinwallimann** [comment]
That makes sense, however I also tried using
```
import org.apache.spark.sql.functions.col
val mapColumns: Array[Column] = dataFrame.columns.map(col)
```
which fails with the NamePlaceholder exception.

So it can't be only because of the `Column` type, there must be something implementation-specific, but I couldn't figure out yet, what it is.

**Comment by cerveada** [comment]
`dataFrame.columns.map(col)` This creates a new generic column instead of getting one from the dataframe. The column is not associated with dataframe so it makes sense it doesn't work.

`col` Is supposed to be used inside `select`.
