### ISSUE TITLE
Error java.lang.NoSuchMethodError on run

### ISSUE THREAD

**Issue by mauriciosfriso** [AbsaOSS/ABRiS#175]
Hi. I'm trying to read a avro topic from comfluent into spark using your example, but when the program starting I get this error:

> Exception in thread "main" java.lang.NoSuchMethodError: io.confluent.kafka.serializers.subject.TopicNameStrategy.subjectName(Ljava/lang/String;ZLorg/apache/avro/Schema;)Ljava/lang/String;
	at za.co.absa.abris.avro.registry.SchemaSubject$.usingTopicNameStrategy(SchemaSubject.scala:41)
	at za.co.absa.abris.config.FromStrategyConfigFragment.andTopicNameStrategy(Config.scala:165)
	at MovimientosCasino$.main(MovimientosCasino.scala:32)
	at MovimientosCasino.main(MovimientosCasino.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

I looked in ABRiS and Confluent implementation of this code, but I can't figure out what is the problem.

I'm using: Spark: 3.0.1, ABRiS: 4.0.1 and Confluent libraries 6.0.1

> ./spark-submit --class ConfluentKafkaAvroReader --master spark://mydomain:7077  --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.1,org.apache.spark:spark-avro_2.12:3.0.1 --jars https://repo1.maven.org/maven2/za/co/absa/abris_2.12/4.0.1/abris_2.12-4.0.1.jar,https://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/6.0.1/kafka-avro-serializer-6.0.1.jar,https://packages.confluent.io/maven/io/confluent/kafka-schema-serializer/6.0.1/kafka-schema-serializer-6.0.1.jar,https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/6.0.1/kafka-schema-registry-client-6.0.1.jar spark.jar

**Comment by cerveada** [comment]
Hello,
Abris is using confluent version `5.3.4`. 

The newer version were causing compatibility issues with libraries used by Spark (details in #165). 

I recommend using the same version.
