### ISSUE TITLE
passing schema-registry SSL config to abris

### ISSUE THREAD

**Issue by sivasai-quartic** [AbsaOSS/ABRiS#179]
we have configured ssl to schema registry to access over https protocol. below are properties we need to pass while creating the client
```
"schema.registry.ssl.ca.location": "/home/itsme/CARoot.pem",
"schema.registry.ssl.certificate.location": "/home/itsme/broker.schema-registry.pem",
"schema.registry.ssl.key.location": "/home/itsme/key.schema-registry.keystore.pem"
```

Just wanted to check, is there a way to pass these properties to abris client to create the https connection, I have tried adding this in key conf and value conf and getting this error

```
Traceback (most recent call last):

py4j.protocol.Py4JJavaError: An error occurred while calling z:za.co.absa.abris.avro.functions.from_confluent_avro.
: za.co.absa.abris.avro.read.confluent.SchemaManagerException: Could not get the id of the latest version for subject 'topic-key'
	at za.co.absa.abris.avro.read.confluent.SchemaManager.getLatestVersionId(SchemaManager.scala:59)
	at za.co.absa.abris.avro.read.confluent.SchemaManager.resolveSchemaId(SchemaManager.scala:40)
	at za.co.absa.abris.avro.read.confluent.SchemaManager.schemaId$lzycompute(SchemaManager.scala:34)
	at za.co.absa.abris.avro.read.confluent.SchemaManager.schemaId(SchemaManager.scala:34)
	at za.co.absa.abris.avro.read.confluent.SchemaManager.downloadSchema(SchemaManager.scala:76)
	at za.co.absa.abris.avro.functions$.from_confluent_avro(functions.scala:87)
	at za.co.absa.abris.avro.functions.from_confluent_avro(functions.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:149)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1143)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1054)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:394)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:212)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:256)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:515)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:507)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getLatestSchemaMetadata(CachedSchemaRegistryClient.java:275)
	at za.co.absa.abris.avro.read.confluent.SchemaManager.$anonfun$getLatestVersionId$2(SchemaManager.scala:56)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at za.co.absa.abris.avro.read.confluent.SchemaManager.getLatestVersionId(SchemaManager.scala:56)
	... 17 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:456)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:323)
	at sun.security.validator.Validator.validate(Validator.java:271)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:223)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
	... 42 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:451)
	... 48 more
```

**Comment by cerveada** [comment]
Which version of Abris do you use?

**Comment by sivasai-quartic** [comment]
Im using 3.2.0 version of abris. i was able to resolve this error by passing 
```-Djavax.net.ssl.trustStore=/kafka.schema-registry.truststore.jks -Djavax.net.ssl.trustStorePassword=pwd -Djavax.net.ssl.keyStore=kafka.schema-registry.keystore.jks -Djavax.net.ssl.keyStorePassword=pwd
```
But end up getting exception

```
py4j.protocol.Py4JJavaError: An error occurred while calling z:za.co.absa.abris.avro.functions.from_confluent_avro.
: za.co.absa.abris.avro.read.confluent.SchemaManagerException: Could not get the id of the latest version for subject 'telemetry_ordered-key'
	at za.co.absa.abris.avro.read.confluent.SchemaManager.getLatestVersionId(SchemaManager.scala:59)
	at za.co.absa.abris.avro.read.confluent.SchemaManager.resolveSchemaId(SchemaManager.scala:40)
	at za.co.absa.abris.avro.read.confluent.SchemaManager.schemaId$lzycompute(SchemaManager.scala:34)
	at za.co.absa.abris.avro.read.confluent.SchemaManager.schemaId(SchemaManager.scala:34)
	at za.co.absa.abris.avro.read.confluent.SchemaManager.downloadSchema(SchemaManager.scala:76)
	at za.co.absa.abris.avro.functions$.from_confluent_avro(functions.scala:87)
	at za.co.absa.abris.avro.functions.from_confluent_avro(functions.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative names present
	at sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
	at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:149)
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1143)
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1054)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:394)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:212)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:256)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:515)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:507)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getLatestSchemaMetadata(CachedSchemaRegistryClient.java:275)
	at za.co.absa.abris.avro.read.confluent.SchemaManager.$anonfun$getLatestVersionId$2(SchemaManager.scala:56)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at za.co.absa.abris.avro.read.confluent.SchemaManager.getLatestVersionId(SchemaManager.scala:56)
	... 17 more
Caused by: java.security.cert.CertificateException: No subject alternative names present
	at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:156)
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:100)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:457)
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:431)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:230)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
	... 42 more
```
any help on this ?

**Comment by cerveada** [comment]
This seems to be a security issue between `schema registry client` and `schema registry`. So you can try their documentation.

If you need to set any configs to schema registry client. You can use the approach described here:
https://github.com/AbsaOSS/ABRiS/tree/branch-3.2#schema-registry-security-settings (for Abris 3.x)

**Comment by nate-kuhl** [comment]
@cerveada The schema registry I'm trying to connect to uses a SSL/Certificate authentication method. Do you know how I would set the `securityRegistryConfig` to point to the credentials in the following files:
```
client.keystore.p12
 client.truststore.jks
 ```
 
 I can only find [examples](https://github.com/AbsaOSS/ABRiS/tree/branch-3.2#schema-registry-security-settings) for connecting to registries with basic authentication methods.

**Comment by cerveada** [comment]
Sorry, I don't know that. This is the setting for `schema registry client` from confluent. Abris just uses that client for communication with schema registry.

You can check the documentation
https://docs.confluent.io/platform/current/schema-registry/security/index.html

And the source code
https://github.com/confluentinc/schema-registry/blob/master/client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java

Abris just takes the config map and provides it to the client.
- In Abris 3.x.x there is one map with config for both Abris and the registry client
- In Abris 4.x.x the map for the client is clearly separated 
But otherwise it's the same.

If you or @sivasai-quartic figure it out, please share an example of how to do it, so people have easier time in the future.

**Comment by cerveada** [comment]
@ nate-kuhl have you been able to solve the issue?
