### ISSUE TITLE
Schema registry error

### ISSUE THREAD

**Issue by moyphilip** [AbsaOSS/ABRiS#209]
I keep hitting an error when I run my jar. However, when I run it on spark-shell it runs fine. I also checked my aws security groups and the master and slave are able to hit the registry.

Any idea what is causing this?

```
    val kafkaOptions = Map(
      "kafka.bootstrap.servers" -> s"server",
      "kafka.security.protocol" -> "SSL",
      "kafka.ssl.endpoint.identification.algorithm" -> "",
      "kafka.ssl.truststore.location" -> "client.truststore.jks",
      "kafka.ssl.truststore.password" -> "pwd",
      "kafka.ssl.keystore.type" -> "PKCS12",
      "kafka.ssl.key.password" -> "pwd",
      "kafka.ssl.keystore.location" -> "client.keystore.p12",
      "kafka.ssl.keystore.password" -> "pw",
      AbrisConfig.SCHEMA_REGISTRY_URL -> "url",
      "basic.auth.credentials.source" -> "USER_INFO",
      "basic.auth.user.info" -> "usr:pwd"
    )
```

Error when hitting registry.

```
diagnostics: User class threw exception: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 2]; error code: 50005
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:236)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:265)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:524)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:516)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getLatestSchemaMetadata(CachedSchemaRegistryClient.java:275)
	at za.co.absa.abris.avro.read.confluent.SchemaManager.getSchemaMetadataBySubjectAndVersion(SchemaManager.scala:64)
	at za.co.absa.abris.avro.read.confluent.SchemaManager.getSchemaBySubjectAndVersion(SchemaManager.scala:53)
	at za.co.absa.abris.avro.read.confluent.SchemaManager.getSchema(SchemaManager.scala:44)
	at za.co.absa.abris.config.FromSchemaDownloadingConfigFragment.usingSchemaRegistry(Config.scala:194)
````

**Comment by cerveada** [comment]
The character '<' must be getting there somehow. Could it come from the subject?

**Comment by kevinwallimann** [comment]
Hi @moyphilip The '<' character in the exception looks like the beginning of a HTML error page returned by schema registry. Since it works with spark-shell, I'd guess there should be a difference in your setup of spark-submit.

**Comment by moyphilip** [comment]
this spark-submit doesnt work:
```
spark-submit \
--master yarn \
--deploy-mode cluster \
--files /home/hadoop/kafka_security/client.truststore.jks,/home/hadoop/kafka_security/client.keystore.p12 \
--class com.stash.data.source.PgStreamerTest /home/hadoop/PgStreamer.jar
```
but this one does:
```
spark-submit \
--repositories https://packages.confluent.io/maven \
--master yarn --deploy-mode cluster \
--files /home/hadoop/kafka_security/client.truststore.jks,/home/hadoop/kafka_security/client.keystore.p12 \
--class com.stash.data.source.PgStreamerTest /home/hadoop/PgStreamer.jar
```

my dependencies are:
```
object Dependencies {
  lazy val sparkVersion = "3.0.0"

  def sparkDependencies(sparkVersion: String): Seq[ModuleID] = Seq(
    "org.apache.spark"          %% "spark-sql"                       % sparkVersion          % "provided",
    "org.apache.spark"          %% "spark-core"                      % sparkVersion          % "provided",
    "org.apache.spark"          %% "spark-hive"                      % sparkVersion          % "provided",
    "org.apache.spark"           % "spark-sql-kafka-0-10_2.12"       % sparkVersion,
    "org.apache.spark"           % "spark-streaming-kafka-0-10_2.12" % sparkVersion,
    "org.apache.spark"          %% "spark-avro"                      % sparkVersion
  )

  lazy val commonDependencies = Seq(
    "com.github.scopt"          %% "scopt"          % "3.7.0",
    "org.scalamock"             %% "scalamock"      % "4.1.0" % Test,
    "org.scalatest"             %% "scalatest"      % "3.0.4" % Test,
    "org.apache.logging.log4j"   % "log4j-api"      % "2.8.2"
  )
  lazy val PgStreamerDependencies = sparkDependencies(sparkVersion) ++ Seq(
    "za.co.absa"                        % "abris_2.12"                   % "4.1.0",
    "org.apache.kafka"                  % "kafka-clients"                % "2.6.0",
    "io.delta"                          %% "delta-core"                  % "0.7.0",
    "com.typesafe"                      % "config"                       % "1.3.2",
    "org.apache.hadoop"                 % "hadoop-aws"                   % "2.7.1" % "provided",
    "org.postgresql"                    % "postgresql"                   % "9.4.1212",
    "org.joda"                          % "joda-convert"                 % "2.0.1",
    "org.apache.commons"                % "commons-lang3"                % "3.1",
    "io.spray"                          %% "spray-json"                  % "1.3.4",
    "com.amazonaws"                     % "aws-java-sdk"                 % "1.11.342" % "provided",
    "org.mockito"                       % "mockito-all"                  % "1.9.5",
  )
}
```

and merge strategy is:
```
lazy val assemblySettings = Seq(
  assemblyOption in assembly := (assemblyOption in assembly).value.copy(includeScala = true),
  assemblyOutputPath in assembly := file(s"dist/${name.value}/${name.value}.jar"),

  assemblyMergeStrategy in assembly := {
    case "META-INF/services/org.apache.spark.sql.sources.DataSourceRegister" => MergeStrategy.concat
    case PathList("org", "apache", xs @ _*) => MergeStrategy.last
    case PathList("META-INF", xs @ _*) => MergeStrategy.discard
    case conf if conf.matches("application.*.conf") => MergeStrategy.concat
    case conf if conf.matches("config.json") => MergeStrategy.discard
    case x => MergeStrategy.first
  }
)
```

**Comment by moyphilip** [comment]
found the issue.
`case PathList("META-INF", xs @ _*) => MergeStrategy.discard` should be 
`case PathList("META-INF", "MANIFEST.MF") => MergeStrategy.discard`
