### ISSUE TITLE
`internalCreateDataFrame` error

### ISSUE THREAD

**Issue by dantswain** [AbsaOSS/ABRiS#28]
Hi, I'm trying to use version 2.2.2 with Spark 2.2.1 and am running into this error:

```
java.lang.NoSuchMethodError: org.apache.spark.sql.SQLContext.internalCreateDataFrame(Lorg/apache/spark/rdd/RDD;Lorg/apache/spark/sql/types/StructType;Z)Lorg/apache/spark/sql/Dataset
```

I can't share all of the code but I think this is the relevant part:

```
 val SchemaRegistryConf = Map(
    SchemaManager.PARAM_SCHEMA_REGISTRY_URL ->
      "redacted",
    SchemaManager.PARAM_SCHEMA_REGISTRY_TOPIC -> Topic,
    SchemaManager.PARAM_VALUE_SCHEMA_NAMING_STRATEGY ->
      SchemaManager.SchemaStorageNamingStrategies.TOPIC_NAME,
    SchemaManager.PARAM_VALUE_SCHEMA_ID -> "latest"
  )

  val logger = Logger(LoggerFactory.getLogger("ProgramTrackFilter"))

  def getStream(spark: SparkSession, bootstrap_servers: String): DataFrame = {
    spark.readStream
      .format(KafkaSource)
      .option("kafka.bootstrap.servers", BootstrapServers)
      .option("subscribe", Topic)
      .fromConfluentAvro("value", None, Some(SchemaRegistryConf))(
        RETAIN_ORIGINAL_SCHEMA
      )
  }

  /* Spark Launcher
   * @param args
   */
  def main(args: Array[String]): Unit = {
    val spark = SparkSession.builder.getOrCreate()

    val df = getStream(spark, BootstrapServers)

    df.printSchema()

    val q =
      df.select("*").writeStream.outputMode("append").format("console").start()

    q.awaitTermination()
  }
```

The output of `printSchema` looks correct - I believe I'm getting the right schema.  The kafka settings are all correct as well.

Is there any other information I can provide short of actually providing the schema and data (which I can't do, unfortunately)?

More of the stacktrace:

```
9/02/08 16:28:55 ERROR StreamExecution: Query [id = 7b47f349-a947-49b2-81ab-c4de6eb928f9, runId = f1fea6a5-b2cb-4261-aa35-678970a323a4] terminated with error
java.lang.NoSuchMethodError: org.apache.spark.sql.SQLContext.internalCreateDataFrame(Lorg/apache/spark/rdd/RDD;Lorg/apache/spark/sql/types/StructType;Z)Lorg/apache/spark/sql/Dataset;
        at org.apache.spark.sql.kafka010.KafkaSource.getBatch(KafkaSource.scala:301)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatch$2$$anonfun$apply$7.apply(StreamExecution.scala:614)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatch$2$$anonfun$apply$7.apply(StreamExecution.scala:610)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at org.apache.spark.sql.execution.streaming.StreamProgress.foreach(StreamProgress.scala:25)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at org.apache.spark.sql.execution.streaming.StreamProgress.flatMap(StreamProgress.scala:25)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatch$2.apply(StreamExecution.scala:610)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatch$2.apply(StreamExecution.scala:610)
        at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:279)
        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
        at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runBatch(StreamExecution.scala:609)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatches$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(StreamExecution.scala:306)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatches$1$$anonfun$apply$mcZ$sp$1.apply(StreamExecution.scala:294)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatches$1$$anonfun$apply$mcZ$sp$1.apply(StreamExecution.scala:294)
        at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:279)
        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anonfun$org$apache$spark$sql$execution$streaming$StreamExecution$$runBatches$1.apply$mcZ$sp(StreamExecution.scala:294)
        at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56)
        at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runBatches(StreamExecution.scala:290)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:206)
```

**Comment by felipemmelo** [comment]
Hi @dantswain , thanks for the report. I'll investigate and come back to you asap. Cheers.

**Comment by hemanshupaliwa7** [comment]
Did this issue got resolved? Any Hint. My same code used to work before on my local and now it's not working when i moved the code to production env

**Comment by dantswain** [comment]
@hemanshupaliwa7 I ended up not using this library :/  I did, however, discover that my topic is compacted.  I do not know if that was the cause of this error not.

**Comment by felipemmelo** [comment]
Hi guys, sorry for the late reply, have been quite busy. 

@hemanshupaliwa7 , the error message seems to be related to some binary incompatibility. Can you share your Spark, Kafka and Kafka integration versions? Also, how are you producing your data, is it by using Confluent Kafka Producer?

**Comment by KenpachiRules** [comment]
@hemanshupaliwa7  For easy verification just check for spark.driver.extraClassPath and spark.executor.extraClassPath and see which version of spark-sql jar is getting loaded , it should be spark-sql-2.3 minimum because the signature of SparkSession.internalCreateDataFrame has changed between 2.2 and 2.3 spark , there is an additional boolean parameter.

**Comment by mxolisiz** [comment]
I had this issue when using a lower version of Spark. had to point my SPARK_HOME to a higher version of Spark(2.4.0)

**Comment by felipemmelo** [comment]
If any issues, please feel free to reopen it.
