### ISSUE TITLE
Dependency conflict when using with spark 2.3.x

### ISSUE THREAD

**Issue by jquadrino** [AbsaOSS/ABRiS#51]
This is occurs when using version `3.0.0` of ABRiS in scala.
```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.avro.Schema.getLogicalType()Lorg/apache/avro/LogicalType;
	at org.apache.spark.sql.avro.SchemaConverters$.toSqlTypeHelper(SchemaConverters.scala:66)
	at org.apache.spark.sql.avro.SchemaConverters$.toSqlTypeHelper(SchemaConverters.scala:105)
	at org.apache.spark.sql.avro.SchemaConverters$$anonfun$1.apply(SchemaConverters.scala:82)
	at org.apache.spark.sql.avro.SchemaConverters$$anonfun$1.apply(SchemaConverters.scala:81)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.avro.SchemaConverters$.toSqlTypeHelper(SchemaConverters.scala:81)
	at org.apache.spark.sql.avro.SchemaConverters$.toSqlTypeHelper(SchemaConverters.scala:105)
	at org.apache.spark.sql.avro.SchemaConverters$$anonfun$1.apply(SchemaConverters.scala:82)
	at org.apache.spark.sql.avro.SchemaConverters$$anonfun$1.apply(SchemaConverters.scala:81)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.avro.SchemaConverters$.toSqlTypeHelper(SchemaConverters.scala:81)
	at org.apache.spark.sql.avro.SchemaConverters$.toSqlType(SchemaConverters.scala:46)
	at za.co.absa.abris.avro.format.SparkAvroConversions$.toSqlType(SparkAvroConversions.scala:106)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.dataType$lzycompute(AvroDataToCatalyst.scala:43)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.dataType(AvroDataToCatalyst.scala:43)
	at org.apache.spark.sql.catalyst.expressions.Alias.toAttribute(namedExpressions.scala:163)
	at org.apache.spark.sql.catalyst.plans.logical.Project$$anonfun$output$1.apply(basicLogicalOperators.scala:51)
	at org.apache.spark.sql.catalyst.plans.logical.Project$$anonfun$output$1.apply(basicLogicalOperators.scala:51)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.catalyst.plans.logical.Project.output(basicLogicalOperators.scala:51)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.schema$lzycompute(QueryPlan.scala:157)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.schema(QueryPlan.scala:157)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:75)
	at 
```

**Comment by cerveada** [comment]
Hello, it looks like wrong version of **org.apache.avro** is in use. Avro 1.8 or higher should be ok. Abris uses 1.8.2. My guess is that in your app it's overwriten to some older version. Could you check that please?

**Comment by jquadrino** [comment]
Hi, I checked and the only library with an Avro dependency is Abris, the only other libraries are spark-* 2.3.0 including the spark streaming kafka jar. I tried removing the avro class definitions from the jar and loading avro 1.8.2 in the classpath but that does not work either.

**Comment by jquadrino** [comment]
I switched to an uber jar and used spark 2.4.1, this is the error:
```

**Comment by jquadrino** [comment]
I noticed that this issue changes when rerunning
```
Caused by: java.lang.ClassNotFoundException: io.confluent.kafka.serializers.AbstractKafkaAvroSerDeConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

**Comment by jquadrino** [comment]
Uber jar contains all relevant confluent libraries, @5.1.0
```
[info] Including: commons-compiler-3.0.8.jar
[info] Including: antlr4-runtime-4.7.jar
[info] Including: orc-core-1.4.1-nohive.jar
[info] Including: xmlenc-0.52.jar
[info] Including: commons-httpclient-3.1.jar
[info] Including: commons-io-2.4.jar
[info] Including: commons-net-2.2.jar
[info] Including: commons-collections-3.2.2.jar
[info] Including: aircompressor-0.8.jar
[info] Including: orc-mapreduce-1.4.1-nohive.jar
[info] Including: log4j-1.2.17.jar
[info] Including: commons-lang-2.6.jar
[info] Including: commons-configuration-1.6.jar
[info] Including: commons-digester-1.8.jar
[info] Including: parquet-column-1.8.2.jar
[info] Including: commons-beanutils-1.7.0.jar
[info] Including: commons-beanutils-core-1.8.0.jar
[info] Including: protobuf-java-2.5.0.jar
[info] Including: gson-2.2.4.jar
[info] Including: hadoop-auth-2.6.5.jar
[info] Including: apacheds-kerberos-codec-2.0.0-M15.jar
[info] Including: parquet-common-1.8.2.jar
[info] Including: parquet-encoding-1.8.2.jar
[info] Including: parquet-hadoop-1.8.2.jar
[info] Including: parquet-format-2.3.1.jar
[info] Including: apacheds-i18n-2.0.0-M15.jar
[info] Including: api-asn1-api-1.0.0-M20.jar
[info] Including: api-util-1.0.0-M20.jar
[info] Including: curator-framework-2.6.0.jar
[info] Including: parquet-jackson-1.8.2.jar
[info] Including: curator-client-2.6.0.jar
[info] Including: jline-0.9.94.jar
[info] Including: curator-recipes-2.6.0.jar
[info] Including: htrace-core-3.0.4.jar
[info] Including: arrow-vector-0.8.0.jar
[info] Including: hadoop-hdfs-2.6.5.jar
[info] Including: arrow-format-0.8.0.jar
[info] Including: flatbuffers-1.2.0-3f79e055.jar
[info] Including: arrow-memory-0.8.0.jar
[info] Including: jsr305-3.0.2.jar
[info] Including: slf4j-api-1.7.25.jar
[info] Including: joda-time-2.9.9.jar
[info] Including: jackson-core-2.7.9.jar
[info] Including: hppc-0.7.2.jar
[info] Including: spark-streaming_2.11-2.3.0.jar
[info] Including: jetty-util-6.1.26.jar
[info] Including: xercesImpl-2.9.1.jar
[info] Including: spark-sql-kafka-0-10_2.11-2.3.0.jar
[info] Including: xml-apis-1.3.04.jar
[info] Including: kafka-clients-0.10.0.1.jar
[info] Including: hadoop-mapreduce-client-app-2.6.5.jar
[info] Including: lz4-1.3.0.jar
[info] Including: hadoop-mapreduce-client-common-2.6.5.jar
[info] Including: spark-streaming-kafka-0-10_2.11-2.3.0.jar
[info] Including: maven-plugin-api-2.0.6.jar
[info] Including: maven-project-2.0.6.jar
[info] Including: maven-settings-2.0.6.jar
[info] Including: hadoop-yarn-common-2.6.5.jar
[info] Including: maven-model-2.0.6.jar
[info] Including: plexus-utils-3.0.15.jar
[info] Including: plexus-container-default-1.0-alpha-9-stable-1.jar
[info] Including: junit-3.8.1.jar
[info] Including: classworlds-1.1-alpha-2.jar
[info] Including: maven-profile-2.0.6.jar
[info] Including: maven-artifact-manager-2.0.6.jar
[info] Including: maven-repository-metadata-2.0.6.jar
[info] Including: maven-artifact-2.0.6.jar
[info] Including: wagon-provider-api-1.0-beta-2.jar
[info] Including: maven-plugin-registry-2.0.6.jar
[info] Including: kafka-avro-serializer-5.1.0.jar
[info] Including: hadoop-yarn-api-2.6.5.jar
[info] Including: kafka-schema-registry-client-5.1.0.jar
[info] Including: common-config-5.1.0.jar
[info] Including: common-utils-5.1.0.jar
[info] Including: zookeeper-3.4.13.jar
[info] Including: audience-annotations-0.5.0.jar
[info] Including: jaxb-api-2.2.2.jar
[info] Including: stax-api-1.0-2.jar
[info] Including: netty-3.10.6.Final.jar
[info] Including: jackson-jaxrs-1.9.13.jar
[info] Including: jackson-xc-1.9.13.jar
[info] Including: guice-3.0.jar
[info] Including: javax.inject-1.jar
[info] Including: aopalliance-1.0.jar
[info] Including: cglib-2.2.1-v20090111.jar
[info] Including: hadoop-yarn-client-2.6.5.jar
[info] Including: zkclient-0.10.jar
[info] Including: guice-servlet-3.0.jar
[info] Including: hadoop-mapreduce-client-core-2.6.5.jar
[info] Including: asm-3.1.jar
[info] Including: jettison-1.1.jar
[info] Including: jaxb-impl-2.2.3-1.jar
[info] Including: slf4j-log4j12-1.7.16.jar
[info] Including: hadoop-yarn-server-common-2.6.5.jar
[info] Including: leveldbjni-all-1.8.jar
[info] Including: hadoop-mapreduce-client-shuffle-2.6.5.jar
[info] Including: hadoop-mapreduce-client-jobclient-2.6.5.jar
[info] Including: spark-launcher_2.11-2.3.0.jar
[info] Including: spark-kvstore_2.11-2.3.0.jar
[info] Including: jackson-databind-2.6.1.jar
[info] Including: jackson-annotations-2.6.7.jar
[info] Including: spark-network-common_2.11-2.3.0.jar
[info] Including: netty-all-4.1.17.Final.jar
[info] Including: commons-lang3-3.5.jar
[info] Including: metrics-core-3.1.5.jar
[info] Including: commons-crypto-1.0.0.jar
[info] Including: spark-network-shuffle_2.11-2.3.0.jar
[info] Including: spark-unsafe_2.11-2.3.0.jar
[info] Including: jets3t-0.9.4.jar
[info] Including: httpcore-4.4.1.jar
[info] Including: httpclient-4.5.jar
[info] Including: commons-codec-1.13.jar
[info] Including: activation-1.1.1.jar
[info] Including: bcprov-jdk15on-1.52.jar
[info] Including: java-xmlbuilder-1.1.jar
[info] Including: base64-2.3.8.jar
[info] Including: javax.servlet-api-3.1.0.jar
[info] Checking every *.class/*.jar file's SHA-1.
[info] Merging files...
```

**Comment by jquadrino** [comment]
Using an uber jar approach, I am able to reduce a lot of errors and handle dependencies easier. I want to be able to put together a build solution for scala users. 

Currently seeing this trace
```
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.codegen.CodegenContext.boxedType
```
build.sbt
```
name := "sink"
version := "0.1"
scalaVersion := "2.11.12"

javacOptions ++= Seq("-encoding", "UTF-8")
javacOptions ++= Seq("-source", "1.8", "-target", "1.8", "-Xlint")

resolvers += "confluent" at "http://packages.confluent.io/maven/"

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-avro" % "2.4.1",
  "za.co.absa" %% "abris" % "3.0.0"
)
assemblyMergeStrategy in assembly := {
  case PathList("META-INF", xs @ _*) => MergeStrategy.discard
  case PathList("org", "apache", "spark", "sql", "avro", xs @ _*) => MergeStrategy.first
  case PathList("org", "apache", "spark", xs @ _*) => MergeStrategy.discard
  case x => MergeStrategy.first
}

```
spark-submit
```
spark-submit --master local \
--packages org.apache.spark:spark-sql_2.11:2.4.1,org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.1,org.apache.hadoop:hadoop-aws:2.7.1 \
--class Sink target/scala-2.11/sink-assembly-0.1.jar
```

**Comment by jquadrino** [comment]
one thing to note, I am copying the uber jar to `/usr/local/spark/jars`, otherwise this does not work at all.

**Comment by jquadrino** [comment]
Full trace
```
Caused by: java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.codegen.CodegenContext.boxedType(Lorg/apache/spark/sql/types/DataType;)Ljava/lang/String;
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst$$anonfun$doGenCode$1.apply(AvroDataToCatalyst.scala:75)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst$$anonfun$doGenCode$1.apply(AvroDataToCatalyst.scala:73)
	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.nullSafeCodeGen(Expression.scala:437)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.doGenCode(AvroDataToCatalyst.scala:73)
	at org.apache.spark.sql.catalyst.expressions.Expression$$anonfun$genCode$2.apply(Expression.scala:108)
	at org.apache.spark.sql.catalyst.expressions.Expression$$anonfun$genCode$2.apply(Expression.scala:105)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.catalyst.expressions.Expression.genCode(Expression.scala:105)
	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.nullSafeCodeGen(Expression.scala:436)
	at org.apache.spark.sql.catalyst.expressions.GetStructField.doGenCode(complexTypeExtractors.scala:126)
	at org.apache.spark.sql.catalyst.expressions.Expression$$anonfun$genCode$2.apply(Expression.scala:108)
	at org.apache.spark.sql.catalyst.expressions.Expression$$anonfun$genCode$2.apply(Expression.scala:105)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.catalyst.expressions.Expression.genCode(Expression.scala:105)
	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.nullSafeCodeGen(Expression.scala:436)
	at org.apache.spark.sql.catalyst.expressions.GetStructField.doGenCode(complexTypeExtractors.scala:126)
	at org.apache.spark.sql.catalyst.expressions.Expression$$anonfun$genCode$2.apply(Expression.scala:108)
	at org.apache.spark.sql.catalyst.expressions.Expression$$anonfun$genCode$2.apply(Expression.scala:105)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.catalyst.expressions.Expression.genCode(Expression.scala:105)
	at org.apache.spark.sql.catalyst.expressions.BinaryExpression.nullSafeCodeGen(Expression.scala:525)
	at org.apache.spark.sql.catalyst.expressions.BinaryExpression.defineCodeGen(Expression.scala:508)
	at org.apache.spark.sql.catalyst.expressions.EqualTo.doGenCode(predicates.scala:621)
	at org.apache.spark.sql.catalyst.expressions.Expression$$anonfun$genCode$2.apply(Expression.scala:108)
	at org.apache.spark.sql.catalyst.expressions.Expression$$anonfun$genCode$2.apply(Expression.scala:105)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.catalyst.expressions.Expression.genCode(Expression.scala:105)
	at org.apache.spark.sql.execution.FilterExec.org$apache$spark$sql$execution$FilterExec$$genPredicate$1(basicPhysicalOperators.scala:139)
	at org.apache.spark.sql.execution.FilterExec$$anonfun$13.apply(basicPhysicalOperators.scala:179)
	at org.apache.spark.sql.execution.FilterExec$$anonfun$13.apply(basicPhysicalOperators.scala:163)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
```

**Comment by jquadrino** [comment]
Spark 2.3.0 uses Avro 1.7.7
https://github.com/apache/spark/blob/v2.3.0/pom.xml#L142

This library uses Spark 2.3.0 and also Avro 1.8.2.

**Comment by cerveada** [comment]
Yes, this is due to dependency on spark-avro 2.4.4 which needs Avro 1.8+. 

We are planing to relase a version for Scala 2.12 and spark 2.4.4 soon, but you could also explicitly declare dependency on avro 1.8. in your app and overwrite the one that comes from spark you are including.

Howewer **abris doesn't fails to build for scala.** The problem commes from your app using spark 2.3 which in turn overrides the dependency on avor to 2.7.

**Comment by cerveada** [comment]
New version (3.0.1) was just released, but it takes like six hours to get to maven central. 

If you want to use spark 2.4.x try the new version, it should work well. For spark 2.3.x you still need to have a dependency on avro 2.8.

**Comment by jquadrino** [comment]
Great, thank you! I will give the new release a try.
