### ISSUE TITLE
Decode each individual payload using its respective schema id from registry

### ISSUE THREAD

**Issue by jquadrino** [AbsaOSS/ABRiS#55]
Is this possible with ABRiS? I am currently using the latest schema for payloads with differing schema ids and the result is a Malformed Record exception from spark deserializer.

```
Caused by: org.apache.spark.SparkException: Malformed records are detected in record parsing.
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.nullSafeEval(AvroDataToCatalyst.scala:65)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.UnsafeExternalRowSorter.sort(UnsafeExternalRowSorter.java:216)
	at org.apache.spark.sql.execution.SortExec$$anonfun$1.apply(SortExec.scala:108)
	at org.apache.spark.sql.execution.SortExec$$anonfun$1.apply(SortExec.scala:101)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:403)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:409)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by felipemmelo** [comment]
Hi @jquadrino , this is not possible with Spark as each Dataframe can only have one schema. 

Cheers,

Felipe.

**Comment by jquadrino** [comment]
This is not quite compatible with confluent then, each payload has a schema
id and using a different schema or global schema will introduce error for
evolving or large schemas.

**Comment by felipemmelo** [comment]
Well, that depends on how we approach compatibility and which tool we are talking about.. Taking into consideration Spark limitations in terms of Dataframe schemas, then yes, Spark itself is not compatible.

On the other hand, considering that vanilla Spark would break on Confluent Avro data and Abris won't, then Abris is compatible with that format, although there is no way to change the schema in a per record basis.

Anyway, since this is not an Abris issue, I'll close the issue. Feel free to reopen if needed.
