### ISSUE TITLE
pyspark issue while deserilization

### ISSUE THREAD

**Issue by sparkheo7** [AbsaOSS/ABRiS#68]
My code works fine in local environment. but same this fails with below mentioned error on my cluster environment.
Let me know what I am missing over here.

Environment :- Pyspark 2.4.0
Spark session command :-     
spark = SparkSession \
        .builder \
        .appName(app_name)\
        .config('spark.jars.packages', 'org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.0,za.co.absa:abris_2.11:3.0.2,mysql:mysql-connector-java:8.0.16,org.apache.avro:avro:1.9.1') \
        .config('spark.jars.repositories','http://packages.confluent.io/maven')\
        .enableHiveSupport()\
        .getOrCreate()

Error :- 
Caused by: org.apache.spark.SparkException: Malformed records are detected in record parsing.
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.nullSafeEval(AvroDataToCatalyst.scala:70)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.serializefromobject_doConsume_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.agg_doAggregateWithoutKey_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1405)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.getWriterSchema(AvroDataToCatalyst.scala:107)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.decodeConfluentAvro(AvroDataToCatalyst.scala:101)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.decode(AvroDataToCatalyst.scala:83)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.nullSafeEval(AvroDataToCatalyst.scala:61)
	... 16 more

**Comment by sparkheo7** [comment]
This is how I am calling api
        jvm_gateway = spark_context._gateway.jvm
        abris_avro = jvm_gateway.za.co.absa.abris.avro
        naming_strategy = getattr(getattr(abris_avro.read.confluent.SchemaManager, "SchemaStorageNamingStrategies$"),
                                  "MODULE$").TOPIC_NAME()
        logger.info("SchemaStorageNamingStrategy: for topic " + topic + " is " + str(naming_strategy))

        schema_registry_config_dict = {"schema.registry.url": schema_registry_url,
                                       "schema.registry.topic": topic,
                                       "value.schema.id": "latest",
                                       "value.schema.naming.strategy": naming_strategy}

        conf_map = get_scala_map(jvm_gateway, schema_registry_config_dict)

        deserialized_df = data_frame.select(
            Column(abris_avro.functions.from_confluent_avro(data_frame._jdf.col("value"), conf_map))
                .alias("data")).select("data.*")

**Comment by cerveada** [comment]
Fixed in 3.0.3

**Comment by sparkheo7** [comment]
Thank you for quick response
