### ISSUE TITLE
Confluent Schema Registry with Basic Authentication

### ISSUE THREAD

**Issue by haribabubonthu** [AbsaOSS/ABRiS#75]
How to use from_confluent_avro when schema registry is secured.
we need to pass below parameters for authentication
basic.auth.credentials.source=USER_INFO
schema.registry.basic.auth.user.info=<SR_API_KEY>:<SR_API_SECRET>
schema.registry.url=https://hostname

How to pass this parameters using schema manager

**Comment by xavtx1** [comment]
same problem here

**Comment by felipemmelo** [comment]
Hi guys, sorry for the late reply, I've been OOO this week. Will get into this issue by the beginning of next week. 

Cheers.

**Comment by felipemmelo** [comment]
Hi @haribabubonthu and @xavtx1 ,

I've just updated Schema Manager to receive all configurations provided. The branch is [this](https://github.com/AbsaOSS/ABRiS/tree/feature/schema_registry_auth). The bit that was changed is [here](https://github.com/AbsaOSS/ABRiS/blob/feature/schema_registry_auth/src/main/scala/za/co/absa/abris/avro/read/confluent/SchemaManager.scala#L191).

Could you please have a look if it solves your problem? If it does, we'll merge it to master and deploy to Maven Central.

Thanks in advance.

**Comment by haribabubonthu** [comment]
Hi thanks  for looking  into the  issue.  I will look tonight  and I will let you  know  the result. Regards, HariOn 18-Nov-2019 18:03, Felipe Melo <notifications@github.com> wrote:Hi @haribabubonthu and @xavtx1 ,
I've just updated Schema Manager to receive all configurations provided. The branch is this. The bit that was changed is here.
Could you please have a look if it solves your problem? If it does, we'll merge it to master and deploy to Maven Central.
Thanks in advance.

**Comment by haribabubonthu** [comment]
Hi @felipemmelo I am trying to create schemaRegistryConfig with below configurations and i am getting below error
val schemaRegistryConfig = Map(
  SchemaManager.PARAM_SCHEMA_REGISTRY_URL          -> "https://schema-registry-url",
  SchemaManager.PARAM_SCHEMA_REGISTRY_TOPIC        -> "test.topic"
)

java.lang.NoClassDefFoundError: Could not initialize class za.co.absa.abris.avro.read.confluent.SchemaManager$

1) Can you please provide jar of latest code for scala 2.11
2) what is the SchemaManager configuration for below paramters
basic.auth.credentials.source
schema.registry.basic.auth.user.info

**Comment by xavtx1** [comment]
Hi @haribabubonthu if you can share an example of the code you are currently employed, it would be very useful

**Comment by haribabubonthu** [comment]
Hi @felipemmelo  Is it possible to provide jar for scala 2.11 target??
I am getting errors while making it as package in maven

**Comment by haribabubonthu** [comment]
Hi @xavtx1 
1) In Databricks first add abris dependency jar 

2) Then import za.co.absa.abris.avro.read.confluent.SchemaManager

3) val schemaRegistryConfig = Map(
  SchemaManager.PARAM_SCHEMA_REGISTRY_URL          -> "sr_url",
  SchemaManager.PARAM_SCHEMA_REGISTRY_TOPIC        -> "test.topic"
)

At this point i am getting error. So i am requesting @felipemmelo  to provide jar

**Comment by cerveada** [comment]
This could help you to build for 2.11 
https://github.com/AbsaOSS/ABRiS/wiki/How-to-cross-compile-Abris

**Comment by haribabubonthu** [comment]
I am able to build for 2.11 and i have added it to databricks.

I am passing below map values

val schemaRegistryConfig1 = Map(
  SchemaManager.PARAM_SCHEMA_REGISTRY_URL          -> "https://srurl",
  SchemaManager.PARAM_SCHEMA_REGISTRY_TOPIC        -> "bw-connect.admin.VBPA4.AVRO",
  SchemaManager.PARAM_KEY_SCHEMA_NAMING_STRATEGY -> SchemaManager.SchemaStorageNamingStrategies.TOPIC_NAME,
  SchemaManager.PARAM_KEY_SCHEMA_ID -> "latest",
  "client.basic.auth.credentials.source" -> "USER_INFO", 
  "client.schema.registry.basic.auth.user.info" -> "srkey:srvalue",
  "specific.avro.reader" -> "true"
)

But still i am getting 401 unauthorized error..

za.co.absa.abris.avro.read.confluent.SchemaManagerException: Could not get the id of the latest version for subject 'bw-connect.admin.VBPA4.AVRO-key'

at za.co.absa.abris.avro.read.confluent.SchemaManager$.getLatestVersionId(SchemaManager.scala:149)
	at za.co.absa.abris.avro.schemas.SchemaLoader$.getSchemaId(SchemaLoader.scala:105)
	at za.co.absa.abris.avro.schemas.SchemaLoader$.loadFromSchemaRegistry(SchemaLoader.scala:80)
	at za.co.absa.abris.avro.schemas.SchemaLoader$.loadFromSchemaRegistryKey(SchemaLoader.scala:58)
	at za.co.absa.abris.avro.parsing.utils.AvroSchemaUtils$.loadForKey(AvroSchemaUtils.scala:57)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.loadSchemaFromRegistry(AvroDataToCatalyst.scala:131)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.avroSchema$lzycompute(AvroDataToCatalyst.scala:52)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.avroSchema(AvroDataToCatalyst.scala:50)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.dataType$lzycompute(AvroDataToCatalyst.scala:46)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.dataType(AvroDataToCatalyst.scala:46)
	at org.apache.spark.sql.catalyst.expressions.Alias.toAttribute(namedExpressions.scala:176)
	at org.apache.spark.sql.catalyst.plans.logical.Project$$anonfun$output$1.apply(basicLogicalOperators.scala:57)
	at org.apache.spark.sql.catalyst.plans.logical.Project$$anonfun$output$1.apply(basicLogicalOperators.scala:57)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.catalyst.plans.logical.Project.output(basicLogicalOperators.scala:57)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.schema$lzycompute(QueryPlan.scala:169)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.schema(QueryPlan.scala:169)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:81)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withPlan(Dataset.scala:3488)
	at org.apache.spark.sql.Dataset.select(Dataset.scala:1361)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-660227710488497:1)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-660227710488497:52)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-660227710488497:54)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-660227710488497:56)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$$iw$$iw$$iw$$iw.<init>(command-660227710488497:58)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$$iw$$iw$$iw.<init>(command-660227710488497:60)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$$iw$$iw.<init>(command-660227710488497:62)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$$iw.<init>(command-660227710488497:64)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read.<init>(command-660227710488497:66)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$.<init>(command-660227710488497:70)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$.<clinit>(command-660227710488497)
	at line2fa8dec74f884d2f9851530f4a5df61146.$eval$.$print$lzycompute(<notebook>:7)
	at line2fa8dec74f884d2f9851530f4a5df61146.$eval$.$print(<notebook>:6)
	at line2fa8dec74f884d2f9851530f4a5df61146.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:215)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:679)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:632)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:368)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:345)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:238)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:233)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:48)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:271)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:48)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:345)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:639)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:485)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:597)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:390)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Unauthorized; error code: 401
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:230)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:256)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:515)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:507)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getLatestSchemaMetadata(CachedSchemaRegistryClient.java:275)
	at za.co.absa.abris.avro.read.confluent.SchemaManager$$anonfun$1.apply$mcI$sp(SchemaManager.scala:147)
	at za.co.absa.abris.avro.read.confluent.SchemaManager$$anonfun$1.apply(SchemaManager.scala:147)
	at za.co.absa.abris.avro.read.confluent.SchemaManager$$anonfun$1.apply(SchemaManager.scala:147)
	at scala.util.Try$.apply(Try.scala:192)
	at za.co.absa.abris.avro.read.confluent.SchemaManager$.getLatestVersionId(SchemaManager.scala:147)
	at za.co.absa.abris.avro.schemas.SchemaLoader$.getSchemaId(SchemaLoader.scala:105)
	at za.co.absa.abris.avro.schemas.SchemaLoader$.loadFromSchemaRegistry(SchemaLoader.scala:80)
	at za.co.absa.abris.avro.schemas.SchemaLoader$.loadFromSchemaRegistryKey(SchemaLoader.scala:58)
	at za.co.absa.abris.avro.parsing.utils.AvroSchemaUtils$.loadForKey(AvroSchemaUtils.scala:57)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.loadSchemaFromRegistry(AvroDataToCatalyst.scala:131)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.avroSchema$lzycompute(AvroDataToCatalyst.scala:52)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.avroSchema(AvroDataToCatalyst.scala:50)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.dataType$lzycompute(AvroDataToCatalyst.scala:46)
	at za.co.absa.abris.avro.sql.AvroDataToCatalyst.dataType(AvroDataToCatalyst.scala:46)
	at org.apache.spark.sql.catalyst.expressions.Alias.toAttribute(namedExpressions.scala:176)
	at org.apache.spark.sql.catalyst.plans.logical.Project$$anonfun$output$1.apply(basicLogicalOperators.scala:57)
	at org.apache.spark.sql.catalyst.plans.logical.Project$$anonfun$output$1.apply(basicLogicalOperators.scala:57)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.catalyst.plans.logical.Project.output(basicLogicalOperators.scala:57)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.schema$lzycompute(QueryPlan.scala:169)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.schema(QueryPlan.scala:169)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:81)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withPlan(Dataset.scala:3488)
	at org.apache.spark.sql.Dataset.select(Dataset.scala:1361)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-660227710488497:1)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-660227710488497:52)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-660227710488497:54)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-660227710488497:56)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$$iw$$iw$$iw$$iw.<init>(command-660227710488497:58)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$$iw$$iw$$iw.<init>(command-660227710488497:60)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$$iw$$iw.<init>(command-660227710488497:62)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$$iw.<init>(command-660227710488497:64)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read.<init>(command-660227710488497:66)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$.<init>(command-660227710488497:70)
	at line2fa8dec74f884d2f9851530f4a5df61146.$read$.<clinit>(command-660227710488497)
	at line2fa8dec74f884d2f9851530f4a5df61146.$eval$.$print$lzycompute(<notebook>:7)
	at line2fa8dec74f884d2f9851530f4a5df61146.$eval$.$print(<notebook>:6)
	at line2fa8dec74f884d2f9851530f4a5df61146.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:215)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply$mcV$sp(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal$$anonfun$repl$1.apply(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:679)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:632)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:197)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:368)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$8.apply(DriverLocal.scala:345)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:238)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:233)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:48)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:271)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:48)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:345)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:644)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:639)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:485)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:597)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:390)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)

**Comment by felipemmelo** [comment]
Thanks for confirming @haribabubonthu .

**Comment by xavtx1** [comment]
I have also been able to deserialize at least locally, without any problem. 
Please you can merge to master and publish the artifact. 
Then I will try to do the test from Databricks. At the moment, trying to generate a fat jar, using the same code in Databricks has given authentication error.

**Comment by felipemmelo** [comment]
Hi @xavtx1 and @haribabubonthu , sorry for the late reply, will do it by the end of the day.

**Comment by felipemmelo** [comment]
Version 3.1.0 now available at Maven Central.
