### ISSUE TITLE
Memory leak due to usage of IdentityHashMap in CachedSchemaRegistryClient

### ISSUE THREAD

**Issue by muthamizhan-a** [AbsaOSS/ABRiS#84]
https://github.com/AbsaOSS/ABRiS/blob/ec704f58b83d1ff6121761f0f611718b45649b3e/pom.xml#L59

Hi,
I have been using this library it's quite handy & useful. While we observed a critical bug that is causing due to usage of IdentityHashMap in CachedSchemaRegistryClient on this schema-registry version . Confluent already fixed this issue by using HashMap. You will have to upgrade the **confluent.version** to overcome this issue.

**Reference**
[Issue ticket](https://github.com/confluentinc/schema-registry/pull/1009)
[source code](https://github.com/confluentinc/schema-registry/blob/5.3.0-post/client/src/main/java/io/confluent/kafka/schemaregistry/client/CachedSchemaRegistryClient.java)

**Error Trace**
` java.lang.IllegalStateException: Too many schema objects created for topic-value!
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:153)
	at za.co.absa.abris.avro.read.confluent.SchemaManager$.register(SchemaManager.scala:199)
	at za.co.absa.abris.avro.parsing.utils.AvroSchemaUtils$.registerIfCompatibleSchema(AvroSchemaUtils.scala:95)
	at za.co.absa.abris.avro.parsing.utils.AvroSchemaUtils$.registerIfCompatibleValueSchema(AvroSchemaUtils.scala:79)
	at za.co.absa.abris.avro.parsing.utils.AvroSchemaUtils$.registerSchema(AvroSchemaUtils.scala:132)
	at za.co.absa.abris.avro.sql.CatalystDataToAvro.za$co$absa$abris$avro$sql$CatalystDataToAvro$$registerSchema(CatalystDataToAvro.scala:76)
	at za.co.absa.abris.avro.sql.CatalystDataToAvro$$anonfun$1.apply(CatalystDataToAvro.scala:44)
	at za.co.absa.abris.avro.sql.CatalystDataToAvro$$anonfun$1.apply(CatalystDataToAvro.scala:43)
	at scala.Option.flatMap(Option.scala:171)
	at za.co.absa.abris.avro.sql.CatalystDataToAvro.nullSafeEval(CatalystDataToAvro.scala:43)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:117)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:116)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1394)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:146)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:67)
	at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:66)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by cerveada** [comment]
Hello, 
thanks for letting us know.

In Maven repository there is no version `5.1.1`. It looks like the fixed version was not released yet.

**Comment by felipemmelo** [comment]
Hi @muthamizhan-a , we've just updated the Confluent version. It's in the master branch. Would you please confirm if it solves the issue?

**Comment by cerveada** [comment]
The update is now included in Abris 3.1.1.

**Comment by felipemmelo** [comment]
Since it seems to be solved by version 3.1.1, we're closing the this issue.

**Comment by muthamizhan-a** [comment]
Thank you for fixing this issue! :-)
